# This is the folder that contains the rule yaml files
# Any .yaml file inside will be loaded as a rule
rules_folder: rules1

# How often ElastAlert will query Elasticsearch
run_every:
  minutes: 1

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 2 # in config.yaml

# The Elasticsearch hostname and port where logs are stored
es_host: ls-master.a910.tak-cslab.org
es_port: 30092

# Optional: Increase connection timeout to avoid read timeout issues
es_conn_timeout: 120
writeback_timeout: 120


# The index on es_host which is used for metadata storage
# This version avoids @timestamp mapping conflict
writeback_index: elastalert_status_v2

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

# Logging configuration for debugging ElastAlert behavior
#logging:
#  version: 1
#  disable_existing_loggers: false
#  formatters:
#    logline:
#      format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'
#  handlers:
#    console:
#      class: logging.StreamHandler
#      formatter: logline
#      level: DEBUG
#      stream: ext://sys.stderr
#  loggers:
#    elastalert:
#      level: DEBUG
#      handlers: [console]
#      propagate: false
